name: "PNet"
op {
  input: "data"
  input: "conv1_w"
  input: "conv1_b"
  output: "conv1"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 3
  }
}
op {
  input: "conv1"
  input: "conv1_Slope"
  output: "conv1"
  type: "PRelu"
}
op {
  input: "conv1"
  output: "pool1"
  type: "MaxPool"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
}
op {
  input: "pool1"
  input: "conv2_w"
  input: "conv2_b"
  output: "conv2"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 3
  }
}
op {
  input: "conv2"
  input: "conv2_Slope"
  output: "conv2"
  type: "PRelu"
}
op {
  input: "conv2"
  input: "conv3_w"
  input: "conv3_b"
  output: "conv3"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 3
  }
}
op {
  input: "conv3"
  input: "conv3_Slope"
  output: "conv3"
  type: "PRelu"
}
op {
  input: "conv3"
  input: "conv4-1_w"
  input: "conv4-1_b"
  output: "conv4-1"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 1
  }
}
op {
  input: "conv3"
  input: "conv4-2_w"
  input: "conv4-2_b"
  output: "conv4-2"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 1
  }
}
op {
  input: "conv4-1"
  output: "prob1"
  type: "Softmax"
}
external_input: "data"
external_input: "conv1_w"
external_input: "conv1_b"
external_input: "conv1_Slope"
external_input: "conv2_w"
external_input: "conv2_b"
external_input: "conv2_Slope"
external_input: "conv3_w"
external_input: "conv3_b"
external_input: "conv3_Slope"
external_input: "conv4-1_w"
external_input: "conv4-1_b"
external_input: "conv4-2_w"
external_input: "conv4-2_b"
external_output: "prob1"
external_output: "conv4-2"
